package Buszmngmt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahydul Islam Shajal
 */
import java.sql.*;
import javax.swing.*;
public class Home_frame extends javax.swing.JFrame {

    /**
     * Creates new form Home_frame
     */
    public Home_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_name_label = new javax.swing.JLabel();
        user_name_field = new javax.swing.JTextField();
        pass_label = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user_name_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user_name_label.setText("User Name");

        user_name_field.setBackground(new java.awt.Color(255, 255, 153));
        user_name_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_name_fieldActionPerformed(evt);
            }
        });

        pass_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pass_label.setText("Password");

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 153));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        loginbtn.setBackground(new java.awt.Color(0, 255, 204));
        loginbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(user_name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_name_fieldActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed

        // TODO add your handling code here:
        String user=user_name_field.getText();
        String pass=jPasswordField1.getText();
        
        
          Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            st=cnn.createStatement();
            
               String sql = "select rank from login where username = '"+user+"'and password = '"+pass+"'";
                    rs = st.executeQuery(sql);
                    
                        int rankint=0;
                  while(rs.next()){
                             rankint=rs.getInt("rank");
                              }
                      

                    if (rankint==10)
                    {
                        JOptionPane.showMessageDialog(null,"welcome to Admin");
                                      Adminpanel ap=new Adminpanel();
                    ap.setVisible(true);
                    }
//                    else if (rankint==0)
//                    {
//                       JOptionPane.showMessageDialog(null,"duplicate user access denied"); 
//                    }
                   else if(rankint==1)
                    {
                        
                        
                        String ax=Integer.toString(rankint); //convert int to string
                     new Details_print(ax);// pass the rankint value to the available_bus frame 
//                        new customerdetails(ax);
                        
                        JOptionPane.showMessageDialog(null,"welcome to Counter 1 "); 
                     Ticket_mngmnt tm=new Ticket_mngmnt();
                                  tm.setVisible(true);
                        
                    }
                    
                   else  if(rankint==2)
                    {
                        
                        String ax=Integer.toString(rankint); //convert int to string
                      new Details_print(ax);                         // pass the rankint value to the available_bus frame 
//                        new customerdetails(ax);
                
                        JOptionPane.showMessageDialog(null,"welcome to Counter 2     "); 
                       Ticket_mngmnt tm=new Ticket_mngmnt();
                                  tm.setVisible(true);
                        
                    }
                   else{
                    JOptionPane.showMessageDialog(null,"Error plz enter correct  ");  
                   
                   }
        
        }
            
            
            
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);
            
        }
       
        
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel pass_label;
    private javax.swing.JTextField user_name_field;
    private javax.swing.JLabel user_name_label;
    // End of variables declaration//GEN-END:variables
}
