/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buszmngmt;

/**
 *
 * @author Mahydul Islam Shajal
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Ticket_mngmnt extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_mngmnt
     */
    public Ticket_mngmnt() {
        initComponents();
    }

     public static String pass_bus_root;
   
   
    private void Fillcombo(){
    
      Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql ="  select distinct(bus_root) from bus_root_table ";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String  bus_rootx =rs.getString("bus_root");
               
                             destinations_combo.addItem( bus_rootx );
                              }
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
         
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        destinations_combo = new javax.swing.JComboBox<>();
        des_ok_btn = new javax.swing.JButton();
        root_field = new javax.swing.JTextField();
        bus_combo = new javax.swing.JComboBox<>();
        time_combo = new javax.swing.JComboBox<>();
        bus_nm_time_ok = new javax.swing.JButton();
        bus_name_field = new javax.swing.JTextField();
        bus_time_field = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        amount_field = new javax.swing.JTextField();
        total_field = new javax.swing.JTextField();
        Done = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ticket_combo = new javax.swing.JComboBox<>();
        fill_seat_btn = new javax.swing.JButton();
        reset_seat = new javax.swing.JButton();
        seat_combo = new javax.swing.JComboBox<>();
        fill_tic_btn = new javax.swing.JButton();
        date_combo = new javax.swing.JComboBox<>();
        fill_date_btn = new javax.swing.JButton();
        date_reset_btn = new javax.swing.JButton();
        reset_tic_btn = new javax.swing.JButton();
        tic_combo_field = new javax.swing.JTextField();
        set_ticket = new javax.swing.JButton();
        show_ticket = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        seat_txt_area = new javax.swing.JTextArea();
        date_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        destinations_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinations_comboActionPerformed(evt);
            }
        });

        des_ok_btn.setText("fill root");
        des_ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                des_ok_btnActionPerformed(evt);
            }
        });

        root_field.setText("Show bus Roots");
        root_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                root_fieldActionPerformed(evt);
            }
        });

        bus_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_comboActionPerformed(evt);
            }
        });

        time_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_comboActionPerformed(evt);
            }
        });

        bus_nm_time_ok.setText("Fill bus time");
        bus_nm_time_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_nm_time_okActionPerformed(evt);
            }
        });

        bus_name_field.setText("show Bus Name");
        bus_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_name_fieldActionPerformed(evt);
            }
        });

        bus_time_field.setText("show time");

        reset.setText("Reset ");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        total_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_fieldActionPerformed(evt);
            }
        });

        Done.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Amount");

        jLabel2.setText("Show Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bus_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bus_time_field))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bus_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(time_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(root_field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destinations_combo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(des_ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bus_nm_time_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(des_ok_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(destinations_combo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(root_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bus_nm_time_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(bus_combo)
                    .addComponent(time_combo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bus_name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(bus_time_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amount_field, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total_field, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ticket_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_comboActionPerformed(evt);
            }
        });

        fill_seat_btn.setText("fill seat");
        fill_seat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fill_seat_btnActionPerformed(evt);
            }
        });

        reset_seat.setText("reset");
        reset_seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_seatActionPerformed(evt);
            }
        });

        seat_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat_comboActionPerformed(evt);
            }
        });

        fill_tic_btn.setText("Fill Ticket");
        fill_tic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fill_tic_btnActionPerformed(evt);
            }
        });

        date_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_comboActionPerformed(evt);
            }
        });

        fill_date_btn.setText("Fill Date");
        fill_date_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fill_date_btnActionPerformed(evt);
            }
        });

        date_reset_btn.setText("reset btn");
        date_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_reset_btnActionPerformed(evt);
            }
        });

        reset_tic_btn.setText("reset");
        reset_tic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_tic_btnActionPerformed(evt);
            }
        });

        tic_combo_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        set_ticket.setText("set Ticket");
        set_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_ticketActionPerformed(evt);
            }
        });

        show_ticket.setText("show seat");
        show_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ticketActionPerformed(evt);
            }
        });

        seat_txt_area.setColumns(20);
        seat_txt_area.setRows(5);
        jScrollPane1.setViewportView(seat_txt_area);

        date_field.setText("Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_combo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(date_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ticket_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 79, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(fill_tic_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reset_tic_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(fill_date_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(date_reset_btn))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(set_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(show_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(seat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fill_seat_btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(reset_seat))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fill_date_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticket_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fill_tic_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_tic_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tic_combo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fill_seat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(set_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        destinations_combo.removeAllItems();
        bus_combo.removeAllItems();
        time_combo.removeAllItems();
        seat_combo.removeAllItems();
    }//GEN-LAST:event_resetActionPerformed

    private void des_ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_des_ok_btnActionPerformed
        // TODO add your handling code here:
        Fillcombo();
    }//GEN-LAST:event_des_ok_btnActionPerformed

    private void destinations_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinations_comboActionPerformed
        // TODO add your handling code here:
        
        String destx =(String)destinations_combo.getSelectedItem();
        root_field.setText(destx);
        pass_bus_root=destx;
    }//GEN-LAST:event_destinations_comboActionPerformed

    private void bus_nm_time_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_nm_time_okActionPerformed
        // TODO add your handling code here:
        FillcomboBusname();
    }//GEN-LAST:event_bus_nm_time_okActionPerformed

    private void bus_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_comboActionPerformed
        // TODO add your handling code here:
         String buscombonm =(String)bus_combo.getSelectedItem();
        bus_name_field.setText(buscombonm);
        pass_bus_busname=buscombonm;
    }//GEN-LAST:event_bus_comboActionPerformed

    private void time_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_comboActionPerformed
        // TODO add your handling code here:\
        String timecombo=(String)time_combo.getSelectedItem();
        bus_time_field.setText(timecombo);
        pass_bus_time=timecombo;
    }//GEN-LAST:event_time_comboActionPerformed

    private void seat_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat_comboActionPerformed
        // TODO add your handling code here:
         String seatcomboactn =(String)   seat_combo.getSelectedItem();
        pass_bus_seat=seatcomboactn;
    }//GEN-LAST:event_seat_comboActionPerformed

    private void fill_seat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fill_seat_btnActionPerformed
        // TODO add your handling code here:
        FillcomboSeat();
    }//GEN-LAST:event_fill_seat_btnActionPerformed

    private void date_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_reset_btnActionPerformed
        // TODO add your handling code here:
        date_combo.removeAllItems();
    }//GEN-LAST:event_date_reset_btnActionPerformed

    private void fill_date_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fill_date_btnActionPerformed
        // TODO add your handling code here:
        FillcomboDate();
    }//GEN-LAST:event_fill_date_btnActionPerformed

    private void date_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_comboActionPerformed
        // TODO add your handling code here:
         String datex=(String)date_combo.getSelectedItem();
         date_field.setText(datex);
        pass_bus_tic_date=datex;
    }//GEN-LAST:event_date_comboActionPerformed

    private void fill_tic_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fill_tic_btnActionPerformed
        // TODO add your handling code here:
        FillcomboTicket();
    }//GEN-LAST:event_fill_tic_btnActionPerformed

    private void ticket_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_comboActionPerformed
        // TODO add your handling code here:
         String tickcomact=(String)ticket_combo.getSelectedItem();
        pass_bus_ticket=tickcomact;
        tic_combo_field.setText(pass_bus_ticket);
    }//GEN-LAST:event_ticket_comboActionPerformed
         
    private void reset_tic_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_tic_btnActionPerformed
        // TODO add your handling code here:
        ticket_combo.removeAllItems();
    }//GEN-LAST:event_reset_tic_btnActionPerformed

    int countclk=0;   //for count use countclk
    private void set_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_ticketActionPerformed
        // TODO add your handling code here:
     String update_ticx=pass_bus_ticket;
     String pass_comx_seat=pass_bus_seat;
     String pass_cox_busamexx=pass_bus_busname;
         
     try{
theQuery("update seat_table,bus  set  seat_table.ticket_no='"+update_ticx+"' where bus.bus_id=seat_table.bus_id and bus_name='"+pass_cox_busamexx+"' and seat_table.seat_no='"+pass_comx_seat+"'  ");

}catch(Exception e){
 JOptionPane.showMessageDialog(null,e);

}
     //calculate total
     String amnt=amount_field.getText();
        int ax=Integer.parseInt(amnt);
        countclk++;
        int total=ax*countclk;
        System.out.println(total);
        
        String totalx=Integer.toString(total);
        total_field.setText(totalx);
     
     
    }//GEN-LAST:event_set_ticketActionPerformed

    private void reset_seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_seatActionPerformed
        // TODO add your handling code here:
        seat_combo.removeAllItems();
    }//GEN-LAST:event_reset_seatActionPerformed

    private void show_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ticketActionPerformed
        // TODO add your handling code here:
        String search_suitable_seat=pass_bus_ticket;
        
        
         Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql ="select seat_table.seat_no from seat_table where seat_table.ticket_no='"+search_suitable_seat+"'  ";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String seatmorex=rs.getString("seat_table.seat_no");
                             
                             seat_txt_area.append(" "+seatmorex);
                             
                             
                             
                             
                              }
        
        
            
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
        
    }//GEN-LAST:event_show_ticketActionPerformed

    private void root_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_root_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_root_fieldActionPerformed

    private void bus_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bus_name_fieldActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
        Details_print detp=new Details_print();
        detp.setVisible(true);
        //open new window
    }//GEN-LAST:event_DoneActionPerformed

    private void total_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_fieldActionPerformed

public void theQuery (String query){
    
    Connection con=null;
    Statement st=null;
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            st=con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"query executed");
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    
    }
    
    
    
     public static String pass_bus_busname;
   public static String pass_bus_time;
   
    private void FillcomboBusname(){
    String bus_detx=pass_bus_root;
      Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql =" select bus_name,bus_time_table.bus_dep_time  from bus_root_table,bus,bus_time_table where bus_root_table.bus_id=bus.bus_id and bus_time_table.bus_id=bus.bus_id  and    bus_root='"+bus_detx+"'  ";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String bus_namx  =rs.getString("bus_name");
                             bus_combo.addItem(bus_namx);
                             
                             String bus_timx=rs.getString("bus_time_table.bus_dep_time");
                             time_combo.addItem(bus_timx);
                              }
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
         
    }
    
     public static String pass_bus_seat;
    private void FillcomboSeat(){
    String pass_busnamex=pass_bus_busname;
      Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql =" select seat_table.seat_no from seat_table,bus where seat_table.bus_id=bus.bus_id and seat_table.ticket_no='' and bus.bus_name='"+pass_busnamex+"'  ";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String  seatx =rs.getString("seat_table.seat_no");
               
                            seat_combo.addItem(seatx);
                              }
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
         
    }
    
     public static String pass_bus_tic_date ;
   
   
    private void FillcomboDate(){
    
      Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql ="select distinct(datefix) from ticket_date_table";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String datecmbox  =rs.getString("datefix");
               
                          date_combo.addItem(datecmbox);
                              }
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
         
    }
    
    
     public static String pass_bus_ticket ;
    private void FillcomboTicket(){
    String search_tic_dtx=pass_bus_tic_date;
    //String search_ticbusx=pass_bus_busname;
      Connection cnn=null;
        Statement st=null;
        ResultSet rs=null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection("jdbc:mysql://localhost/user_registration","root","");
            
            st=cnn.createStatement();
            
            
         
                 String sql =" select ticket_date_table.ticket_no from ticket_date_table where ticket_date_table.ticket_no not in(select seat_table.ticket_no from seat_table) and datefix='"+search_tic_dtx+"'  ";
                   rs = st.executeQuery(sql);


              while(rs.next()){
                             String pass_tic_nox  =rs.getString("ticket_date_table.ticket_no");
               
                            ticket_combo.addItem(pass_tic_nox);
                              }
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_mngmnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_mngmnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_mngmnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_mngmnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_mngmnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JTextField amount_field;
    private javax.swing.JComboBox<String> bus_combo;
    public static javax.swing.JTextField bus_name_field;
    private javax.swing.JButton bus_nm_time_ok;
    public static javax.swing.JTextField bus_time_field;
    private javax.swing.JComboBox<String> date_combo;
    public static javax.swing.JTextField date_field;
    private javax.swing.JButton date_reset_btn;
    private javax.swing.JButton des_ok_btn;
    private javax.swing.JComboBox<String> destinations_combo;
    private javax.swing.JButton fill_date_btn;
    private javax.swing.JButton fill_seat_btn;
    private javax.swing.JButton fill_tic_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_seat;
    private javax.swing.JButton reset_tic_btn;
    public static javax.swing.JTextField root_field;
    private javax.swing.JComboBox<String> seat_combo;
    public static javax.swing.JTextArea seat_txt_area;
    private javax.swing.JButton set_ticket;
    private javax.swing.JButton show_ticket;
    public static javax.swing.JTextField tic_combo_field;
    private javax.swing.JComboBox<String> ticket_combo;
    private javax.swing.JComboBox<String> time_combo;
    public static javax.swing.JTextField total_field;
    // End of variables declaration//GEN-END:variables
}
